### ISSUE TITLE
[デザイン] StatusBar&SearchBarとTableViewの重なりが見づらい

### ISSUE THREAD

**Issue by kiriem** [rayRyou/Takeout-map#1]
## 起こっていること
* ListのTableViewを下にスクロールしていくと、StatusBar&SearchBarの上部にまで表示がかかってしまう
![IMG_6382](https://user-images.githubusercontent.com/8245567/79855046-61477f80-8405-11ea-9092-a71b60838f1b.jpg)

## 改善提案
* 背景を透明ではなく、TableViewの backgroundColor と同じにする

## 再現環境
* iPhoneXS Max / iOS13.4

**Comment by rayRyou** [comment]
@kiriem header colorを変える方向で対処します。

**Comment by kiriem** [comment]
@rayRyou マージありがとうございます！
こちらのissueはクローズしちゃいますね👍
