### ISSUE TITLE
[デザイン] 店舗詳細画面でサムネイル画像上部の余白がある場合とない場合がある

### ISSUE THREAD

**Issue by kiriem** [rayRyou/Takeout-map#2]
## 起こっていること
* 店舗詳細画面のサムネイル画像上部の余白がある場合とない場合がある

### 空白なし
![IMG_6384](https://user-images.githubusercontent.com/8245567/79855753-55a88880-8406-11ea-9fbd-760b7b714fbd.jpg)

### 空白あり
![IMG_6383](https://user-images.githubusercontent.com/8245567/79855759-58a37900-8406-11ea-9c5b-5c79e316f0a1.jpg)

## 解決案
* Aspect Fill すれば解決？

## 再現環境
 * iPhone XS Max / iOS 13.4

**Comment by rayRyou** [comment]
@kiriem 画像サイズがそれぞれ違うのではみ出て表示されてしまうケースもあるので、fitで対応しています。
sizeToFit()して、画像の高さを取得してから各パーツの位置を調整してもいいかも。

**Comment by kiriem** [comment]
@rayRyou 
シュミレータ（iPhone11ProMax, iPhone11Pro, iPhone11）で確認したら特に問題なく表示されてますね...🤔
リリース版とGitHub版でなにか違うのかもしれないです。

### iPhone 11 Pro Max
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-21 at 20 26 46](https://user-images.githubusercontent.com/8245567/79860926-812f7100-840e-11ea-9652-5e14944cb2c5.png)

### iPhone 11 Pro

![Simulator Screen Shot - iPhone 11 Pro - 2020-04-21 at 20 26 44](https://user-images.githubusercontent.com/8245567/79860938-87bde880-840e-11ea-99b8-3f9a80eb0e0c.png)
